apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-generator-blog
  namespace: openshift-gitops
spec:
  destination:
    namespace: policy-generator-blog
    # server: https://kubernetes.default.svc
    server: https://api.ma4kmc5.openshiftv4test.com:6443
  project: default
  source:
    path: kustomize
    repoURL: https://github.com/hirokuni-kitahara/grc-policy-generator-blog.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
